<?php

/**
 * @file
 * Contains menu_markup.module
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Render\FormattableMarkup;

use Drupal\menu_markup\Controller\MenuMarkupController;

/**
 * Implements hook_install().
 */
function menu_markup_install() {
  $t = get_t();
  drupal_set_message($t("Congrats! menu_markup settings are available under !link", 
    array( '!link' => l(t('admin/config/menu_markup'),  'admin/config/menu_markup'))
  ));
}

/**
 * Implements hook_menu().
 */
function menu_markup_menu() 
{
  $items['admin/config/system/menu_markup'] = array(
    'title' => 'Menu Markup Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('menu_markup_form'),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );
 
  return $items;
}

/**
 * Admin form to configure markup for menu titles
 */
function menu_markup_form($form, &$form_state) 
{
  $form['menu_markup_configuration'] = array(
    '#type' => 'textarea',
    '#title' => t('Menu Markup Configuration'),
    '#rows' => 15,
    '#required' => TRUE,
  	'#default_value' => variable_get('menu_markup_configuration', ''),
  );
 
  return system_settings_form($form);
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function menu_markup_menu_links_discovered_alter(&$links) 
{
	// Creat a new MenuMarkupController object
	$markup = new MenuMarkupController(Drupal::service('config.factory'), $links);

	// Parse the menu config as performed in the admin panel
	$markup->parseMenuConfig();

	// Rebuild the menu links!
	$links = $markup->rebuildMenuLinks();
}
